name: Deploy iOS & android for testing
on:
  pull_request:
    branches:
      - staging
    types:
      - closed
jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
      - name: Bump version via fastlane
        id: bump
        run: |
          bundle exec fastlane bump_version push:false branch:${{ github.ref_name }}
          echo "::set-output name=new_version::$(version.txt)"

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get
     
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v
      # Checkout Repo code
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Dart Language
        uses: dart-lang/setup-dart@v1.3
      - name: Convert labels to track
        id: labels_to_track
        run: "dart workflows_utils/labels_to_track.dart ${{ join(github.event.pull_request.labels.*.name,' ') }}"
      # Setup Ruby, Bundler, Gemfile & flutter dependencies & Build Android
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

  commit_version_bump:
    name: Commit Version Bump
    needs: [build_ios, build_android]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.email "kiyochinh@gmail.com"
          git config --global user.name "Kiyo Chinh"
      - name: Commit and Tag New Version
        run: |
          new_version="${{ needs.bump_version.outputs.new_version }}"
          git add .
          git commit -m "[Chore] Bump version to $new_version"
          git tag -a "v$new_version" -m "Version $new_version"
          git push origin HEAD:${{ github.ref_name }} --tags